services:
  db:
    image: postgres:18
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/fpfuetsch/dokohub:1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ORIGIN: ${ORIGIN}
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      INVITATION_JWT_SECRET: ${INVITATION_JWT_SECRET}
    ports:
      - 127.0.0.1:5173:5173

volumes:
  pgdata:
